version: "3.9"

services:
  web:
    image: 192.168.0.11:5000/ucla-ssh:latest
    build: .
    ports:
      - "5006:5000"
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=Europe/London
      # - PUBLIC_KEY=yourpublickey #optional
      # - PUBLIC_KEY_FILE=/path/to/file #optional
      # - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      # - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=vagrant #optional
      # - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=vagrant #optional
    # volumes:
    #   - /path/to/appdata/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped
