version: "3.9"

services:
  web:
    image: 192.168.0.11:5000/ucla-ssh:latest
    build: .
    ports:
      - "5006:5000"
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    ports: 
      - "2222:2222"
    environment:
      USER_NAME: vagrant
      USER_PASSWORD: vagrant
      # SUDO_ACCESS: true
      # PASSWORD_ACCESS: true